### ISSUE TITLE
NaN constants

### ISSUE THREAD

**Issue by guicho271828** [Shinmera/float-features#10]
e.g. short-float-NaN?

**Comment by Shinmera** [comment]
The trouble with NaN constants is that there is no single NaN constant for any float representation.

**Comment by guicho271828** [comment]
uum, like positive or negative, or signaling or quiet?
though, operationally they are treated as the same, IMHO
I have a case where I specifically wants to return a NaN, in which case NaN constant will help

**Comment by Shinmera** [comment]
There's 22 bits in the mantissa of a NaN that can be anything, so there's no canonical NaN.

I understand the use-case for converting from other representations where any NaN is treated the same, so I'd be fine with the inclusion of a NaN constant, though it should be clearly stated in the documentation that such constants should not be used for comparison.

I'd be open to a PR to add this feature. I currently lack the time to do the legwork (implementation, documentation, testing) myself.

**Comment by guicho271828** [comment]
yes, I am aware of those 22 bits for the additional information.
I will consider the PR.

**Comment by Symbolics** [comment]
Would the way it is implemented in [ieee-floats](https://github.com/marijnh/ieee-floats/blob/master/ieee-floats.lisp) work here?
```
(cond ((not (zerop significand)) :not-a-number)
				   ((zerop sign) :positive-infinity)
				   (t :negative-infinity))))))
```
I'm converting from ieee-floats to float-features and noticed that we're missing a NaN constant as well.

**Comment by Shinmera** [comment]
No, the point of float-features is to have the actual float-types represent the values, so using keywords defeats that purpose.

**Comment by guicho271828** [comment]
What I suggested above is to provide **an example** float NaN constant, which should not be used for testing NaN. (for that purpose, float-nan-p should be used)
