### ISSUE TITLE
float-bits don't work for negative floats on sbcl

### ISSUE THREAD

**Issue by Bike** [Shinmera/float-features#13]
For example, `(sb-kernel:single-float-bits -0.2379f0) => -1099719665`, so if you call `(float-features-single-float-bits -0.2379f0)` the type declaration makes it fail.

**Comment by Shinmera** [comment]
Ouch. Not sure what the correct course of action is here. Change to sb? Drop the declaration entirely?

**Comment by Bike** [comment]
You can also just do `(ldb (byte 32 0) (sb-kernel:single-float-bits float)`, but yeah, could talk to them about it
