### ISSUE TITLE
Problem with NaN

### ISSUE THREAD

**Issue by Symbolics** [Shinmera/float-features#20]
I'm trying to use double-float-nan, but encountering an error:

```
arithmetic error FLOATING-POINT-INVALID-OPERATION signalled
Operation was (> #<DOUBLE-FLOAT quiet NaN> #<DOUBLE-FLOAT quiet NaN>).
   [Condition of type FLOATING-POINT-INVALID-OPERATION]
```
on this code (last line, condition with `and`):
```
    (cond ((= x double-float-positive-infinity) double-float-positive-infinity)
	  ((> x maxgamd) double-float-positive-infinity)
	  ((and (minusp x) (= 0 (rem x 1))) double-float-nan)
```
For background, the intention is to return `double-float-nan` when `x` is a negative integer. Since it's declared a double, I have to check in a bit of a circuitous way, but that shouldn't affect the ability to return `double-float-nan`.

I can see that NaN is [defined as a constant](https://github.com/Shinmera/float-features/blob/4f9b20472a477d0b82d7e9cdc25a9044a763299c/nan.lisp#L24), and it's symbol is defined in the environment:

```
CL-USER> (describe 'org.shirakumo.float-features:double-float-nan)
FLOAT-FEATURES:DOUBLE-FLOAT-NAN
  [symbol]

DOUBLE-FLOAT-NAN names a constant variable:
  Value: #<DOUBLE-FLOAT quiet NaN>
  Documentation:
    A positive quiet NaN value with zero-cleared payload for double-floats.
    This value should NOT be used for comparison with a float value for the pupose of testing NaN
    because NaN has unused bits (called payload) which are explicitly allowed to store additional information.
    Comparing this value with other NaN representations via = will fail.
    To test if a number is a NaN, use FLOAT-NAN-P.
    
    It is supported on implementations which support BITS-DOUBLE-FLOAT.
    
    Defaults to MOST-POSITIVE-DOUBLE-FLOAT on unsupported implementations.

DOUBLE-FLOAT-NAN names an undefined function
  Assumed type: FUNCTION
```

Any ideas why this can't be returned from a `cond`? The error almost makes it look like SBCL is trying to do a comparison on the value. SBCL is version 2.0.10 on MS Windows.

**Comment by Shinmera** [comment]
Take it up with SBCL. The compiler tries to do something with the float constant to optimise it, but because it's a NAN that triggers the float trap you're seeing. A workaround (for now) is to use the definition of the double float (using `bits-double-float`) instead of the constant, as that avoids the folding.

**Comment by Symbolics** [comment]
Okay, I'll ask over there. Perhaps I need floating point traps enabled.

**Comment by Symbolics** [comment]
Confirmed SBCL bug. This work-around fixes the issue.
