### ISSUE TITLE
ecl implementation of `with-float-traps-masked` looks wrong

### ISSUE THREAD

**Issue by 3b** [Shinmera/float-features#23]
ECL implementation of `with-float-traps-masked` uses keyword arguments to `si::trap-fpe` for `last` and trap names, which should be normal symbols from CL package instead (trap names are names of CL conditions).

The flag argument also looks inverted, should be `NIL` to disable the trap and `T` to enable it.

`si::trap-fpe` should probably also be `ext:trap-fpe`

https://ecl.common-lisp.dev/static/manual/Numbers.html#Numbers-_002d-Floating-point-exceptions

**Comment by 3b** [comment]
yeah, i think that matches my understanding from docs and #ecl (don't have a copy of ecl to test on though).

but now that i read your diff, i notice `:underlow` which probably also won't work right :/

**Comment by 3b** [comment]
Some test that it actually restores the previous setting correctly might be nice (i think failing to do that is why the tests added with it mostly passed), though that would require either adding some abstraction for querying state (and testing that) or testing by behavior (which is complicated by configurations that don't trap in the first place)

**Comment by dkochmanski** [comment]
I'd verify whether the symbol was exported before or after the last release :)

I've changed ecl to signal an error on invalid condition, so the next release will complain on similar occasions (and updated the manual to explicitly say `cl:floating-point-invalid` etc).
