### ISSUE TITLE
Floating point rounding modes

### ISSUE THREAD

**Issue by digikar99** [Shinmera/float-features#24]
Hi, thank you for this library!

I came across [Marco Antoniotti's 2020 paper](https://arxiv.org/abs/2003.03831) who has mentioned a point about rounding modes. A quick look at SBCL revealed the function `SB-INT:GET-FLOATING-POINT-MODES` and `SB-INT:SET-FLOATING-POINT-MODES`, while on CCL, these are `CCL:GET-FPU-MODE` and `CCL:SET-FPU-MODE`. It'd be great if we could wrap these (and other implementations) in a macro such as `(with-rounding-mode (or :nearest :up :down :to-zero) ...)` on these as well as other implementations!

**Comment by Shinmera** [comment]
Sounds good. Now someone just has to go and do the legwork :)

**Comment by digikar99** [comment]
I can give this a try. Another thought that crossed my mind was if it is safe to assume these are thread-local, otherwise if we cannot assume these are thread local, providing the wrapper functions `GET-FLOATING-POINT-ROUNDING-MODE` and `SET-FLOATING-POINT-ROUNDING-MODE` might be better.

**Comment by LdBeth** [comment]
I have made the macro `with-rounding-mode` and tested for CCL and SBCL and found a very funny thing: with the default optimization level, both the compiler would try to constant folding floating point expressions.
Using `(declare (optimize (speed 0) (debug 3) (safety 3)))` to instruct the compiler to not perform too aggressive optimization would make it work for CCL but won't for SBCL.

```
;; CCL
CL-USER> (defun foo ()
           (declare (optimize (speed 0) (debug 3) (safety 3)))
           (with-rounding-mode :negative (- 3.1D0 0.11D0)))
FOO
CL-USER> (foo)
2.9899999999999998D0
```

```
;; SBCL 2.3.0
* (defun foo (a b) ;; has to supply the argument at runtime
           (declare (optimize (speed 0) (safety 3) (debug 3) (space 3)))
           (with-rounding-mode :negative (- a b)))
* (foo 3.1D0 0.11D0)
2.9899999999999998d0
```

The rounding mode setting can and can only be done by set a register in the CPU so there is not much thing can be done for it but most OS should get this to be thread local.

CCL, CMUCL, Mezzano, SBCL all generate assembly by themselves so they are able to support rounding mode setting. I think all other CL (and other programming languages) implementations that does not generate native machine code cannot support this. GNU Common Lisp and other compile to C CLs does not support this unless they include platform dependent code. CLASP seems also does not have relevant code in their source. ABCL has `set-floating-point-modes` but reading the source code reveals it only sets trapping behavior. LispWorks does not seems mention support changing rounding mode.
