### ISSUE TITLE
Rounding modes export

### ISSUE THREAD

**Issue by Homo-carbonis** [Shinmera/float-features#33]
Hello, I was asking for a portable way of setting the rounding mode on discord. It appears float-features has a `with-rounding-mode` macro but it's not exported.
Would it be a good idea to add `get-rounding-mode` and `set-rounding-mode` and also to signal an error if it's used on an implementation where setting the rounding mode isn't supported?

**Comment by Shinmera** [comment]
Signalling an error would be a change in the API and deviate from the documentation, and would also be inconsistent with how `with-float-traps-masked` is implemented.

Is there a particular reason you want a get and set rather than keeping it dynamic extent?

**Comment by Shinmera** [comment]
Done, docs should be updated now too.
